# Generated by Django 4.0 on 2025-11-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('vaccination', 'Vaccination Information'), ('symptoms', 'Symptoms Question'), ('prevention', 'Prevention Tips'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read after reviewing')),
                ('replied', models.BooleanField(default=False, help_text='Mark as replied after responding')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('vaccination', 'Vaccination'), ('symptoms', 'Symptoms'), ('prevention', 'Prevention')], default='general', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FluStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024-2025', help_text='Flu season (e.g., 2024-2025)', max_length=20)),
                ('cases', models.CharField(default='43M', help_text='Number of symptomatic cases', max_length=20)),
                ('deaths', models.CharField(default='38K', help_text='Number of deaths', max_length=20)),
                ('hospitalizations', models.CharField(default='560K', help_text='Number of hospitalizations', max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='High', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the season')),
                ('is_active', models.BooleanField(default=True, help_text='Set this to display on the website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flu Statistic',
                'verbose_name_plural': 'Flu Statistics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='flaticon-patient', help_text='Icon class name (e.g., flaticon-patient, flaticon-hand-washing)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prevention Tip',
                'verbose_name_plural': 'Prevention Tips',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RiskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='flaticon-patient', help_text='Icon class name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Group',
                'verbose_name_plural': 'Risk Groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='symptom_high-fever.png', help_text='Icon filename (e.g., symptom_high-fever.png)', max_length=100)),
                ('is_emergency', models.BooleanField(default=False, help_text='Mark this if it requires immediate medical attention')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['order', 'name'],
            },
        ),
    ]
